version: "3"

services:  
  neo4j:
    image: neo4j:${N4J_VERSION}
    container_name: neo4j
    restart: unless-stopped
    networks:
      - net
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687 
      - 2006:2006
    environment:
      # General
      #- NEO4J_server_config_strict__validation_enabled=false # https://stackoverflow.com/questions/76207890/neo4j-docker-compose-to-kubernetes/77261518
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # APOC & gds  plugins:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*,algo.*
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*,algo.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_trigger_enabled=true
      # Communication
      - NEO4J_server_http_advertised__address=localhost:7687
      - NEO4J_server_bolt_advertised__address=localhost:7474
      # Metrics (only available in enterprise edition)
      #- NEO4J_server_metrics_csv_enabled=false
      #- NEO4J_server_metrics_prometheus_enabled=true
      #- NEO4J_server_metrics_prometheus_endpoint=0.0.0.0:2006
    healthcheck:
      test: wget localhost:7474 || exit 1
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 120s  


networks:
  net:
